#!/usr/bin/env bash

cd "$(dirname "$0")" # Change directory to the folder containing this file
cd ../               # Change directory to project's root folder

# Full pre-push suite: same checks as pre-commit (see README "Health checks"; all-is-well.ts is the
# source of truth).
node --run test
